# -*- coding: utf-8 -*-
"""Conditional probability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Olr_IaXeVZq3BDG_scKdwCeV5LYHGOB_
"""

import tkinter as tk
from tkinter import filedialog, ttk
import csv
import re
import os

class NgramAnalyzerGUI:
    def __init__(self, master):
        self.master = master
        master.title("Probabilidades")

        # Configurar el color de fondo de la ventana principal y los frames
        bg_color = "#ADD8E6"  # Azul pastel
        master.configure(bg=bg_color)

        self.frame_load_csv = tk.Frame(master, bg=bg_color)
        self.frame_load_csv.pack(padx=60, pady=10)

        self.frame_text_entry = tk.Frame(master, bg=bg_color)
        self.frame_text_entry.pack(padx=60, pady=10)

        self.frame_ngram_type = tk.Frame(master, bg=bg_color)
        self.frame_ngram_type.pack(padx=60, pady=10)

        self.frame_calculate_button = tk.Frame(master, bg=bg_color)
        self.frame_calculate_button.pack(padx=60, pady=10)

        self.load_csv_button = tk.Button(self.frame_load_csv, text="Cargar CSV", command=self.load_csv)
        self.load_csv_button.pack(side=tk.LEFT)

        self.text_label = tk.Label(self.frame_text_entry, text="Texto:", bg=bg_color)
        self.text_label.pack(side=tk.LEFT)

        self.text_entry = tk.Entry(self.frame_text_entry)
        self.text_entry.pack(side=tk.LEFT)

        self.ngram_type = tk.StringVar()
        self.ngram_type.set("B")

        self.bigram_radio = tk.Radiobutton(self.frame_ngram_type, text="Bigramas", variable=self.ngram_type, value="B", bg=bg_color)
        self.bigram_radio.pack(side=tk.LEFT)

        self.trigram_radio = tk.Radiobutton(self.frame_ngram_type, text="Trigramas", variable=self.ngram_type, value="T", bg=bg_color)
        self.trigram_radio.pack(side=tk.LEFT)

        self.calculate_button = tk.Button(self.frame_calculate_button, text="Calcular probabilidad conjunta", command=self.calculate_probability)
        self.calculate_button.pack()

    def load_csv(self):
        file_paths = filedialog.askopenfilenames(filetypes=(("Archivos CSV", "*.csv"), ("Todos los archivos", "*.*")))
        if file_paths:
            print("Archivos CSV cargados:")
            ngram_type = self.ngram_type.get()
            valid_files = []
            for file_path in file_paths:
                if ngram_type == "B":
                    if re.search(r'bigramas?|bigrams?', file_path, re.IGNORECASE):
                        valid_files.append(file_path)
                elif ngram_type == "T":
                    if re.search(r'trigramas?|trigrams?', file_path, re.IGNORECASE):
                        valid_files.append(file_path)
            if valid_files:
                for file_path in valid_files:
                    print(file_path)
                self.file_paths = valid_files
            else:
                print("No se encontraron archivos válidos para el tipo de ngrama seleccionado.")

    def load_ngrams_from_csv(self, filename):
        ngrams = {}
        with open(filename, 'r', encoding='utf-8') as file:
            reader = csv.reader(file)
            next(reader)  # Saltamos los encabezados
            for row in reader:
                terms = tuple(row[:-3])
                frequency = int(row[-3])
                ngrams[terms] = frequency
        return ngrams

    def load_ngrams(self, filenames):
        ngrams = []
        for filename in filenames:
            ngram_corpus = self.load_ngrams_from_csv(filename)
            ngrams.append(ngram_corpus)
        return ngrams

    def calculate_joint_probability(self, text, ngrams, n):
        tokens = text.split()
        vocabulary_size = len(set(ngrams.keys()))
        probability_product = 1
        for i in range(len(tokens) - n + 1):
            ngram = tuple(tokens[i:i+n])
            # Aplicar suavizado de Laplace
            probability = (ngrams.get(ngram, 0) + 1) / (sum(ngrams.values()) + vocabulary_size)
            probability_product *= probability
        return probability_product

    def calculate_probability(self):
        if not hasattr(self, 'file_paths') or not self.file_paths:
            print("No se han cargado archivos CSV válidos.")
            return

        # Obtener el texto del cuadro de entrada
        text = self.text_entry.get()

        # Determinar si el usuario seleccionó bigramas o trigramas
        ngram_type = self.ngram_type.get()

        # Calcular la probabilidad conjunta para cada conjunto de n-gramas
        probabilities = []
        for idx, file_path in enumerate(self.file_paths, start=1):
            ngrams = self.load_ngrams_from_csv(file_path)
            if ngram_type == "B":
                probability = self.calculate_joint_probability(text, ngrams, n=2)
            else:
                probability = self.calculate_joint_probability(text, ngrams, n=3)
            filename = os.path.basename(file_path)  # Extraer solo el nombre del archivo
            probabilities.append((idx, filename, probability))

        # Mostrar las probabilidades en una ventana emergente
        result_window = tk.Toplevel(self.master)
        result_window.title("Resultados")
        result_window.geometry("1000x200")

        # Crear un Treeview para mostrar los resultados en forma de tabla
        tree = ttk.Treeview(result_window, columns=("col0","col1", "col2"))
        tree.column("col0", width=80, anchor= "center")
        tree.column("col1", width=80, anchor= "center")
        tree.column("col2", width=80, anchor= "center")

        tree.heading("col0", text="Puesto")
        tree.heading("col1", text="Modelo de lenguaje", anchor= "center")
        tree.heading("col2", text="Probabilidad conjunta", anchor= "center")
        tree.pack(expand=True, fill=tk.BOTH)

        # Insertar los datos en el Treeview
        for idx, (position, filename, probability) in enumerate(probabilities, start=1):
            tree.insert("", "end", values=(position, filename, f"{probability:.25f}"))


root = tk.Tk()
my_gui = NgramAnalyzerGUI(root)
root.mainloop()